#!/usr/bin/env python
#
# Copyright (c) 2010 Julian Andrews.
# All rights reserved.
#
# This file is part of Go Games Screensaver.
#
#    Go Games Screensaver is free software: you can redistribute it and/or 
#    modify it under the terms of the GNU General Public License as 
#    published by the Free Software Foundation, either version 3 of the 
#    License, or (at your option) any later version.
#
#    Go Games Screensaver is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Go Games Screensaver.  If not, see 
#    <http://www.gnu.org/licenses/>.

import sys

try:
    import lib
except ImportError:
    lib_folder = "/usr/share/gogames-screensaver"
    sys.path.insert(0, lib_folder)
    import lib

sys.modules['gogames_screensaver'] = sys.modules['lib']

import gio
import optparse

from gogames_screensaver import gogame
from gogames_screensaver import goban_display

move_num = 160
parser = optparse.OptionParser(usage="usage: %prog [options] <input> <output>")
parser.add_option("-s", "--size", action="store", type="int", default=256, 
                  metavar="SIZE")

def create_thumbnail():
    options, args = parser.parse_args()
    if not len(args) == 2:
        parser.print_help()
        sys.exit(0)
    uri, output_file = args
    gfile = gio.File(uri)
    try:
        data = gfile.load_contents()[0]
        print data
        game_node = gogame.game_nodes_from_data(data)[0]
        for i in range(move_num):
            if game_node.child_nodes == []:
                break
            game_node = game_node[0]
    except (gio.Error, gogame.GogameError), e:
        print e
        return
    gd = goban_display.GobanDisplay()
    gd.game_node = game_node
    try:
        gd.draw_to_file(options.size, output_file)
    except IOError, e:
        # fail silently in this case
        pass
        
if __name__ == "__main__":
    create_thumbnail()
